version: '3.8'

services:
  web:
    build: ./messaging_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./messaging_app:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=messaging_app.settings
      - DB_HOST=db
      - DB_NAME=${MYSQL_DB}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

volumes:
  mysql_data: 