pipeline {
    agent any

    environment {
        // Python virtual environment path
        VENV = "${WORKSPACE}/venv"
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub
                checkout scm
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                    python3 -m venv ${VENV}
                    . ${VENV}/bin/activate
                    pip install -r requirements.txt
                    pip install pytest pytest-cov
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV}/bin/activate
                    pytest --junitxml=test-results/junit.xml --cov=. --cov-report=xml
                '''
            }
        }
    }

    post {
        always {
            // Publish test results
            junit 'test-results/junit.xml'
            
            // Publish coverage report
            cobertura coberturaReportFile: 'coverage.xml'
            
            // Clean up virtual environment
            sh 'rm -rf ${VENV}'
        }
    }
} 