pipeline {
    agent any

    environment {
        // Python virtual environment path
        VENV = "${WORKSPACE}/venv"
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub with credentials
                git branch: 'main',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/yourusername/alx-backend-python.git'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                    python3 -m venv ${VENV}
                    . ${VENV}/bin/activate
                    pip3 install -r messaging_app/requirements.txt
                    pip3 install pytest pytest-cov
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV}/bin/activate
                    cd messaging_app
                    pytest --junitxml=test-results/junit.xml --cov=. --cov-report=xml
                '''
            }
        }
    }

    post {
        always {
            // Publish test results
            junit 'messaging_app/test-results/junit.xml'
            
            // Publish coverage report
            cobertura coberturaReportFile: 'messaging_app/coverage.xml'
            
            // Clean up virtual environment
            sh 'rm -rf ${VENV}'
        }
    }
} 