name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: messaging_app_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DB_NAME: messaging_app_test
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
      DB_PORT: 3306

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r messaging_app/requirements.txt
        pip install pytest pytest-django pytest-cov flake8 flake8-django

    - name: Run Flake8
      run: |
        cd messaging_app
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests with Coverage
      run: |
        cd messaging_app
        pytest --junitxml=test-results/junit.xml --cov=. --cov-report=xml --cov-report=html

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: messaging_app/test-results/junit.xml

    - name: Upload Coverage XML Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report-xml
        path: messaging_app/coverage.xml

    - name: Upload Coverage HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report-html
        path: messaging_app/htmlcov

    - name: Coverage Report
      run: |
        cd messaging_app
        echo "=== Coverage Report ==="
        coverage report
        echo "===================="